apiVersion: v1
kind: Service
metadata:
  name: itstrat
  namespace: default
  labels:
    app: itstrat
spec:
  selector:
    app: itstrat
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
